### ISSUE TITLE
'join host' page, only allow objective assets

### ISSUE THREAD

**Issue by 2i2i** [2i2i/app_2i2i#704]
in the db, there is a table called 'FX' ~ each doc is an assetId and contains the exchange rate (FX) of that asset vs ALGO

if an assetId exists in this table, this asset is called *objective*
else it is called *subjective*

in the 'join host' page, in the caroussell, we show all account x asset combos

if the chosen account x asset is a subjective asset, this account x asset combo cannot be used ~ the account widget tile should transparently overlay a text saying 'subjective assets support coming later' ~ the 'join' button should stay disabled

so this is a change both for the AccountAsset widget and the join host page

**Comment by Androidsignal** [comment]
Implemented.

**Comment by 2i2i** [comment]
need a new PR for this pls
